/*jshint esversion: 6*/

const cards = [
    {rank:'A', suite:'spades'},
    {rank:'2', suite:'spades'},
    {rank:'3', suite:'spades'},
    {rank:'4', suite:'spades'},
    {rank:'5', suite:'spades'},
    {rank:'6', suite:'spades'},
    {rank:'7', suite:'spades'},
    {rank:'8', suite:'spades'},
    {rank:'9', suite:'spades'},
    {rank:'10', suite:'spades'},
    {rank:'J', suite:'spades'},
    {rank:'Q', suite:'spades'},
    {rank:'K', suite:'spades'},
    {rank:'A', suite:'clubs'},
    {rank:'2', suite:'clubs'},
    {rank:'3', suite:'clubs'},
    {rank:'4', suite:'clubs'},
    {rank:'5', suite:'clubs'},
    {rank:'6', suite:'clubs'},
    {rank:'7', suite:'clubs'},
    {rank:'8', suite:'clubs'},
    {rank:'9', suite:'clubs'},
    {rank:'10', suite:'clubs'},
    {rank:'J', suite:'clubs'},
    {rank:'Q', suite:'clubs'},
    {rank:'K', suite:'clubs'},
    {rank:'A', suite:'hearts'},
    {rank:'2', suite:'hearts'},
    {rank:'3', suite:'hearts'},
    {rank:'4', suite:'hearts'},
    {rank:'5', suite:'hearts'},
    {rank:'6', suite:'hearts'},
    {rank:'7', suite:'hearts'},
    {rank:'8', suite:'hearts'},
    {rank:'9', suite:'hearts'},
    {rank:'10', suite:'hearts'},
    {rank:'J', suite:'hearts'},
    {rank:'Q', suite:'hearts'},
    {rank:'K', suite:'hearts'},
    {rank:'A', suite:'dimonds'},
    {rank:'2', suite:'dimonds'},
    {rank:'3', suite:'dimonds'},
    {rank:'4', suite:'dimonds'},
    {rank:'5', suite:'dimonds'},
    {rank:'6', suite:'dimonds'},
    {rank:'7', suite:'dimonds'},
    {rank:'8', suite:'dimonds'},
    {rank:'9', suite:'dimonds'},
    {rank:'10', suite:'dimonds'},
    {rank:'J', suite:'dimonds'},
    {rank:'Q', suite:'dimonds'},
    {rank:'K', suite:'dimonds'}
];

export default cards;
